import styled from "styled-components";
import Head from "next/head";
import dynamic from "next/dynamic";
import Header from "../../components/Header/Header";
import Footer from "../../components/Footer/Footer";

export default function MapPage({ locations }) {
  const Map = dynamic(() => import("../../components/Map/Map"), {
    loading: () => <p>Map is loading</p>,
    ssr: false,
  });
  return (
    <>
      <Head>
        <title>map</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <StyledMobileLayout>
        <Header />
        <main>
          <Map locations={locations} />
        </main>
        <Footer atMapPage />
      </StyledMobileLayout>
    </>
  );
}

const StyledMobileLayout = styled.div`
  display: grid;
  grid-template-rows: 4rem auto 4rem;
  height: 100vh;

  main {
    overflow-y: scroll;
  }
`;
