import styled from "styled-components";
import Head from "next/head";
import Header from "../components/Header/Header";
import Main from "../components/Main/Main";

export default function Home() {
  return (
    <>
      <Head>
        <title>localSports</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <MobileLayout>
        <Header />
        <Main />
      </MobileLayout>
    </>
  );
}

const MobileLayout = styled.div`
  display: grid;
  grid-template-rows: 4rem auto;
  height: 100vh;

  main {
    overflow-y: scroll;
  }
`;
