import styled from "styled-components";
import Head from "next/head";
import Header from "../components/Header/Header";
import Main from "../components/Main/Main";
import Footer from "../components/Footer/Footer";
import FilterMenu from "../components/FilterMenu/FilterMenu";

export default function Home({
  locations,
  onToggleFavorite,
  favorites,
  onShowFilterMenu,
  onFilter,
  onFilterOther,
  onCityFilter,
  onChangeSort,
  filterData,
  filterDataOther,
  cityFilter,
  sortData,
  isShowingFilterMenu,
}) {
  return (
    <>
      <Head>
        <title>localSports</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <StyledMobileLayout>
        <Header onShowFilterMenu={onShowFilterMenu} filterMenu />
        <Main
          locations={locations}
          filterData={filterData}
          onToggleFavorite={onToggleFavorite}
          favorites={favorites}
        />
        {isShowingFilterMenu && (
          <FilterMenu
            onShowFilterMenu={onShowFilterMenu}
            onFilter={onFilter}
            onFilterOther={onFilterOther}
            onCityFilter={onCityFilter}
            onChangeSort={onChangeSort}
            filterData={filterData}
            filterDataOther={filterDataOther}
            cityFilter={cityFilter}
            sortData={sortData}
          />
        )}
        <Footer atHomePage />
      </StyledMobileLayout>
    </>
  );
}

const StyledMobileLayout = styled.div`
  display: grid;
  grid-template-rows: 4rem auto 4rem;
  height: 100svh;

  main {
    overflow-y: scroll;
  }
`;
